version: '3.8'
services: 
    db:
        container_name: mssql_demo
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "Pass@123"
            ACCEPT_EULA: "Y"
        volumes:
            - my-test-volume:/var/opt/mssql
volumes:
    my-test-volume: